# Generated by Django 3.1.1 on 2020-10-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_inactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
