# Generated by Django 3.1.1 on 2020-10-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201001_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inactive',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='inactive',
            name='title',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
