# Generated by Django 3.1.1 on 2020-10-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201002_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='photo',
            field=models.URLField(blank=True, default=None),
        ),
    ]
