# Generated by Django 3.1.4 on 2020-12-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201002_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='photo',
            field=models.BinaryField(blank=True),
        ),
    ]
