# Generated by Django 3.1.4 on 2020-12-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201211_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='photo',
            field=models.URLField(blank=True, default=None),
        ),
    ]
